name: dart_shelf
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.4.0
  compute: ^1.0.2
  dia: ^0.1.3
  dia_body: ^0.1.2
  dia_router: ^0.1.6

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  test: ^1.23.1
