name: dart_conduit
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^4.3.6
  mime: ^1.0.2

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.6
